version: '3'
services:
  mysql:
    image: mariadb:10.4
    volumes:
      - "./data/db:/var/lib/mysql"
    container_name: proz_db
    restart: always
    #command: --default_authentication_plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=proz
      - MYSQL_DATABASE=proz
      - MYSQL_USER=root
      - MYSQL_PASSWORD=proz

  laravel-env:
    build: ./dockerfiles
    container_name: proz_php
    depends_on:
      - mysql
    volumes:
      - ".:/var/www/laravel-boilerplate"
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./dockerfiles/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"

  nginx:
    image: nginx:latest
    container_name: proz_web
    depends_on:
      - laravel-env
    volumes:
      - ".:/var/www/laravel-boilerplate"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8100:80"
    restart: always

  phpmyadmin:
    container_name: proz_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8200:80'
    environment:
      PMA_HOST: proz_db
      MYSQL_ROOT_PASSWORD: proz
